import { ReviewIssue, ReviewOutput, Severity } from "./types";

const MARKER_SUMMARY = "<!-- reviewcerberus-summary -->";
const MARKER_ISSUE = "<!-- reviewcerberus-issue -->";

const SEVERITY_EMOJI: Record<Severity, string> = {
  CRITICAL: "\u{1F534}",
  HIGH: "\u{1F7E0}",
  MEDIUM: "\u{1F7E1}",
  LOW: "\u{1F7E2}",
};

const SEVERITY_ORDER: Record<Severity, number> = {
  CRITICAL: 0,
  HIGH: 1,
  MEDIUM: 2,
  LOW: 3,
};

export function sortIssuesBySeverity(issues: ReviewIssue[]): ReviewIssue[] {
  return [...issues].sort(
    (a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity]
  );
}

export function renderSummaryComment(output: ReviewOutput): string {
  const lines: string[] = [
    MARKER_SUMMARY,
    "# \u{1F415}\u{200D}\u{1F9BA} ReviewCerberus",
    "",
    "## Summary",
    "",
    output.description,
    "",
  ];

  if (output.issues.length === 0) {
    lines.push("## Issues Summary");
    lines.push("");
    lines.push("\u{2705} No issues found during the review.");
    lines.push("");
  } else {
    const sortedIssues = sortIssuesBySeverity(output.issues);

    lines.push("## Issues Summary");
    lines.push("");
    lines.push("| # | Title | Category | Severity | Location |");
    lines.push("|---|-------|----------|----------|----------|");

    sortedIssues.forEach((issue, idx) => {
      const emoji = SEVERITY_EMOJI[issue.severity];
      let location = issue.location[0]?.filename || "-";
      if (issue.location.length > 1) {
        location += ` (+${issue.location.length - 1})`;
      }
      lines.push(
        `| ${idx + 1} | ${issue.title} | ${issue.category} | ${emoji} ${issue.severity} | \`${location}\` |`
      );
    });

    lines.push("");
  }

  lines.push("---");
  lines.push(
    "*Generated by [ReviewCerberus](https://github.com/Kirill89/reviewcerberus)*"
  );

  return lines.join("\n");
}

export function renderLineComment(issue: ReviewIssue): string {
  const emoji = SEVERITY_EMOJI[issue.severity];

  const lines: string[] = [
    MARKER_ISSUE,
    `### ${emoji} ${issue.severity}: ${issue.title}`,
    "",
    `**Category:** ${issue.category}`,
    "",
  ];

  // Add confidence if present
  if (issue.confidence !== undefined && issue.confidence !== null) {
    const rationale = issue.rationale ? ` - ${issue.rationale}` : "";
    lines.push(`**Confidence:** ${issue.confidence}/10${rationale}`);
    lines.push("");
  }

  // Add other locations if multiple
  if (issue.location.length > 1) {
    const otherLocations = issue.location.slice(1).map((loc) => {
      const lineInfo = loc.line ? `:${loc.line}` : "";
      return `\`${loc.filename}${lineInfo}\``;
    });
    lines.push(`**Also affects:** ${otherLocations.join(", ")}`);
    lines.push("");
  }

  lines.push("#### Explanation");
  lines.push("");
  lines.push(issue.explanation);
  lines.push("");
  lines.push("#### Suggested Fix");
  lines.push("");
  lines.push(issue.suggested_fix);

  return lines.join("\n");
}

export { MARKER_SUMMARY, MARKER_ISSUE };
